
import './globals.css'
import type { Metadata } from 'next'
import { Open_Sans } from 'next/font/google'
import { ClerkProvider } from '@clerk/nextjs'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/providers/theme-provider'
import { ModalProvider } from '@/components/providers/modal-provider'
import { SocketProvider } from '@/components/providers/socket-provider'
import { QueryProvider } from '@/components/providers/query-provider'
import { Toaster } from 'sonner'
import { ProgressBarPleas } from '@/components/progress-bar';
import { esES } from "@clerk/localizations";

const font = Open_Sans({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Usemi Call',
  description: 'Generated by create next app',
  manifest: "/manifest.json",
  keywords: ["USM", "Santa Maria", "Universidad", "next13", "pwa", "next-pwa"],
  themeColor: [{ media: "(prefers-color-scheme: dark)", color: "#fff" }],
  viewport:
    "minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover",
  icons: [
    { rel: "usm-icon", url: "/public/icon-128x128.png" },
    { rel: "icon", url: "/public/icon-128x128.png" },
  ],
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider localization={esES}>
      <html lang="es" suppressHydrationWarning>
        <body className={cn(
            font.className,
            'bg-[#F2F3F5] dark:bg-[#313338]' 
          )} >
          <ProgressBarPleas/>
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            enableSystem={false}
            storageKey='usemi-theme'
          >
            <Toaster richColors position='bottom-right' />
            <SocketProvider>
              <ModalProvider/>
              <QueryProvider>
                {children}
              </QueryProvider>
            </SocketProvider>
          </ThemeProvider>
          </body>
      </html>
    </ClerkProvider>
  )
}
